INTRODUCING

BEAST Franchise

Play the Future of Fantasy Baseball NOW!

BEAST Franchise is the first user-based controlled Batting Order Game in Fantasy Baseball. Unlike Old School Fantasy Baseball games you not only choose the players on your team every night, you also choose their batting order.

Here’s how BEAST Franchise works.

1. Pick the Players on your BEAST Franchise team.

2. Set your BEAST Franchise team’s batting order.

3. Earn points as your players bat through your batting order as many times as they can. Every 3 outs the bases reset.

For example:

Suppose you have the following players on your BEAST Franchise team. In real life Chris Davis hits a solo home run in his first at bat. You, however, placed Davis in the 6th spot on your BEAST Franchise batting order. Meanwhile in real life Mike Trout is on 3rd, Jose Bautista is on 2nd, and Robinson Cano is on 1st.

In Old School Fantasy Baseball you’d only earn points for Davis’s solo HR. But in BEAST Franchise you earn points for a Grand Slam as well as the 4 RBIs and the 4 Runs.

The days of hoping Lyle Overbay and Travis Hafner hitting in your Robinson Cano are over. WithBEAST Franchise you finally have full control of your Fantasy Baseball Team.


 

BEAST FRANCHISE is the Ultimate Fantasy Baseball Experience.





PRIVACY POLICY

Your IP Address
Each time that you visit the Site, our web server automatically recognizes your IP address and the web page from which you came. Your IP address is used to help identify you and to gather broad demographic information about you. We also use your IP address to help diagnose problems with our servers, to administer the Site and to better serve you in using the products, services and other features associated with the Site.
Cookies and Action Tags
Cookies: The first time that a user provides an e-mail address in connection with his/her activities at the Site, we assign an identification number to that e-mail address and deploy a cookie to the applicable user's PC. Whenever that user comes back to the Site using the same PC, the cookie allows the Site to identify the user and to recall the user’s e-mail address. If, at any time, a user provides other information in connection with his/her activities on the Site (such as name, address, birth date, gender, etc.), we may store that information, along with the user's e-mail address, in our user database. We may use the information stored in our database: (a) to effectuate the purpose or transaction for which the information was originally provided by a user; (b) to pre-populate information fields in the event that the subject user wishes to purchase products and/or services or sign up for and/or subscribe to services, promotions or other offers in the future; (c) to ensure that a user will not be repeatedly exposed to the same advertisements, offers and/or promotions while visiting the Site; and/or (d) to, in connection with regular communication with a user, include offers, promotions or advertisements that were historically, or are likely to be, of interest to that user. We also use cookies to anonymously track and target the interests of our users to further enhance the experience on the Site. To find out more about cookies, please visit www.cookiecentral.com. To disable and reject cookies, Click Here.
Action Tags: An action tag or a web-beacon (also known as a clear gif or a pixel tag) is a method used to track responses or actions by visitors who view certain advertisements or other information on the Site. Action tags are 1x1 pixel images embedded in a website page that are used to transparently collect information. We may use action tags to count the number of times that visitors click on a particular banner ad or visit the pages of the Site and to provide information about what products/services are viewed or purchased. We reserve the right to retain cookie and action tag data indefinitely. At no time will we share cookie-related, action-tag-related and/or generated information and/or data with third parties.


How We Use Demographic Information and Aggregate Data
We use demographic information to tailor the Site, BEASTfranchise to the interests of our users. Demographic information is shared with third party advertisers so that they can tailor their advertisements to the appropriate audience. Demographic information may also be shared with other third parties.
We reserve the right to provide aggregate or group data about our users for lawful purposes. Aggregate or group data is data that describes the demographics, usage or characteristics of our participants as a group, without disclosing personally identifiable information. You agree to allow us to provide such aggregate data to third parties. By agreeing to the terms of this Privacy Policy, you hereby consent to the disclosure of any record or communication to any third party when we, in our sole discretion, determine the disclosure to be appropriate.


Other Websites
This Site may contain links to third-party owned and/or operated websites. Beast Franchise™ is not responsible for the privacy practices or the content of such websites. In some cases, you may be able to make a purchase through one of these third-party websites. In these instances, you may be required to provide certain information, such as a credit card number, to register or complete a transaction at such website. These third-party websites have separate privacy and data collection practices and Beast Franchise™ has no responsibility or liability relating to them.
Our Security Precautions
We endeavor to safeguard and protect our users’ information. The privacy of your Personal Information is very important to us. The servers that we store personally identifiable information in are kept in a secure physical environment. We have security measures in place to protect the loss, misuse and alteration of Personal Information under our control. When our registration/application process asks users to enter Sensitive Information, and when we store and transmit such Sensitive Information, that information is encrypted and protected with SSL encryption software. While we use SSL encryption to protect Sensitive Information online, we also do everything in our power to protect all user information off-line and online. Unfortunately, no data transmission over the Internet can be guaranteed to be 100% secure. As a result, while we strive to protect your Personal Information, we cannot ensure or warrant the security of any information that you transmit to us, and you do so at your own risk.
However, access to your information is strictly limited, and not accessible to the public. All of our users’ information is restricted in our offices. Only employees who need the information to perform a specific job are granted access to Personal Information. Our employees are dedicated to ensuring the security and privacy of all user information. Employees not adhering to our firm policies are subject to disciplinary action. In compliance with applicable federal and state laws, we shall notify you and any applicable regulatory agencies in the event that we learn of an information security breach with respect to your Personal Information. You will be notified via e-mail in the event of such a breach. Please be advised that notice may be delayed in order to address the needs of law enforcement, determine the scope of network damage, and to engage in remedial measures.


Your Acceptance of these Terms
By using the Site BEASTfranchise, you agree to the terms of our Privacy Policy. We reserve the right, at our discretion, to change, modify, add and/or remove portions of this Privacy Policy at any time. All Privacy Policy changes will take effect immediately upon their posting on the Site. Please check this page periodically for changes. Your continued use of the Site, Services and/or acceptance of our e-mail following the posting of changes to these terms will mean that you accept these changes and agree to continue receiving e-mail from us. If you do not agree to the terms of this Privacy Policy, please unsubscribe by Clicking Here.

13. Proprietary Rights. All Site Material is owned or licensed by or to Beast Franchise™, and is protected under applicable copyrights, trademarks and other proprietary (including, but not limited to, intellectual property) rights. Except as expressly provided in the Agreement, no part of the Site Material may be reproduced, recorded, retransmitted, sold, rented, broadcast, distributed, published, uploaded, posted, publicly displayed, altered to make new works, performed, digitized, compiled, translated or transmitted in any way to any other computer, website or other medium or for any commercial purpose, without Beast Franchise’s™ prior express written consent. Except as expressly provided herein, you are not granted any rights or license to patents, copyrights, trade secrets, rights of publicity or trademarks with respect to any of the Site Material. The posting of information or material at the Site by Beast Franchise™ does not constitute a waiver of any right in such information and materials. Beast Franchise™ reserves all rights not expressly granted hereunder. The “Beast Franchise” name and logo are trademarks of Skyllzone LLC. All custom graphics, icons and service names are trademarks of their rightful owners. All other trademarks are the property of their respective owners. The use of any Beast Franchise™ trademark without Beast Franchise’s™ express written consent is strictly prohibited.
14. Bypassing or Disabling any Portion of the Beast Franchise™ Services or Site. If you bypass or disable any portion of the Beast Franchise™ Services, Beast Franchise™ Shop, Site or associated software including, without limitation, the blocking of cookies or the operation of any other Beast Franchise™ systems, or you attempt to circumvent or tamper with Beast Franchise’s™ Contests or billing methods in any way, you are in violation of the Agreement and Beast Franchise™ may suspend or terminate your Beast Franchise™ Services Account without notice. Termination of your Beast Franchise™ Services Account will not excuse you from any criminal or other civil liabilities that may result from your actions. If your Beast Franchise™ Services Account is terminated for any reason you will, thereafter, be unable to access the Beast Franchise™ Services and/or Beast Franchise™ Shop. 
15. Accessing the Site. You are responsible for obtaining and maintaining, at your own cost and expense, all input/output devices or equipment (such as modems, terminal equipment, computer equipment and software) and communications services (including, without limitation, long distance or local telephone services) necessary to access the Site and for ensuring that such equipment and services are compatible with Beast Franchise’s™ requirements. 
16. Indemnification. You agree to indemnify and hold Beast Franchise™, its parents and subsidiaries, and each of their respective members, officers, directors, employees, agents, co-branders, content licensors and/or other partners, harmless from and against any and all claims, expenses (including reasonable attorneys’ fees), damages, suits, costs, demands and/or judgments whatsoever, made by any third party due to or arising out of: (a) your use of the Site, Beast Franchise™ Services and/or Beast Franchise™ Shop in any way, whatsoever; (b) your breach of the Agreement; (c) any disputed between you and any Members, Third Party Providers, Sources and/or other third parties; (d) any claim that Beast Franchise™ owes any taxes in connection with your use of the Site, Beast Franchise™ Services and/or Beast Franchise™ Shop; and/or (e) your violation of any rights of another individual and/or entity. The provisions of this Section 16 are for the benefit of Beast Franchise™, its parents, subsidiaries and/or affiliates, and each of their respective officers, directors, members, employees, agents, shareholders, licensors, suppliers and/or attorneys. Each of these individuals and entities shall have the right to assert and enforce these provisions directly against you on its own behalf.
17. Disclaimer of Warranties. THE SITE, Beast Franchise™ SERVICES, Beast Franchise™ CONTESTS AND/OR Beast Franchise™ SHOP, ANY CONTENT, FEEDBACK, NEWS FEEDS, Beast Franchise™ SHOP PRODUCTS OR ANY OTHER PRODUCTS AND/OR SERVICES OFFERED THEREIN, ARE PROVIDED TO YOU ON AN “AS IS” AND “AS AVAILABLE” BASIS AND ALL WARRANTIES, EXPRESS AND IMPLIED, ARE DISCLAIMED TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW (INCLUDING, BUT NOT LIMITED TO, THE DISCLAIMER OF ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT OF INTELLECTUAL PROPERTY AND/OR FITNESS FOR A PARTICULAR PURPOSE). IN PARTICULAR, BUT NOT AS A LIMITATION THEREOF, Beast Franchise™ MAKES NO WARRANTY THAT THE SITE, Beast Franchise™ SERVICES, Beast Franchise™ CONTESTS AND/OR Beast Franchise™ SHOP, ANY CONTENT, FEEDBACK, NEWS FEEDS, Beast Franchise™ SHOP PRODUCTS OR ANY OTHER PRODUCTS AND/OR SERVICES OFFERED THEREIN: (A) WILL MEET YOUR REQUIREMENTS; (B) WILL BE UNINTERRUPTED, TIMELY, SECURE, ERROR-FREE OR THAT DEFECTS WILL BE CORRECTED; (C) WILL BE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; (D) WILL HAVE SECURITY METHODS EMPLOYED THAT WILL BE SUFFICIENT AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF THE SITE, OR AGAINST INFRINGEMENT; AND/OR (E) WILL BE ACCURATE OR RELIABLE. THE SITE, Beast Franchise™ SERVICES, Beast Franchise™ CONTESTS AND/OR Beast Franchise™ SHOP, ANY CONTENT, FEEDBACK, NEWS FEEDS, Beast Franchise™ SHOP PRODUCTS OR ANY OTHER PRODUCTS AND/OR SERVICES OFFERED THEREIN MAY CONTAIN BUGS, ERRORS, PROBLEMS OR OTHER LIMITATIONS. Beast Franchise™ WILL NOT BE LIABLE FOR THE AVAILABILITY OF THE UNDERLYING INTERNET CONNECTION ASSOCIATED WITH THE SITE. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM Beast Franchise™, ANY MEMBERS, THIRD PARTY PROVIDERS, SOURCES OR OTHERWISE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE AGREEMENT. 
18. Limitation of Liability. YOU EXPRESSLY UNDERSTAND AND AGREE THAT Beast Franchise™ SHALL NOT BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL AND/OR EXEMPLARY DAMAGES INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF Beast Franchise™ HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), TO THE FULLEST EXTENT PERMISSIBLE BY LAW FOR: (A) THE USE OR THE INABILITY TO USE THE SITE, Beast Franchise™ SERVICES, Beast Franchise™ CONTESTS AND/OR Beast Franchise™ SHOP, ANY CONTENT, FEEDBACK, NEWS FEEDS, Beast Franchise™ SHOP PRODUCTS OR ANY OTHER PRODUCTS AND/OR SERVICES OFFERED THEREIN; (B) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION, CONTENT AND/OR ANY OTHER PRODUCTS PURCHASED OR OBTAINED FROM OR THROUGH THE SITE; (C) THE UNAUTHORIZED ACCESS TO, OR ALTERATION OF, YOUR REGISTRATION DATA; AND (D) ANY OTHER MATTER RELATING TO THE SITE, Beast Franchise™ SERVICES, Beast Franchise™ CONTESTS AND/OR Beast Franchise™ SHOP, ANY CONTENT, FEEDBACK, NEWS FEEDS, Beast Franchise™ SHOP PRODUCTS OR ANY OTHER PRODUCTS AND/OR SERVICES OFFERED THEREIN. THIS LIMITATION APPLIES TO ALL CAUSES OF ACTION, IN THE AGGREGATE INCLUDING, BUT NOT LIMITED TO, BREACH OF CONTRACT, BREACH OF WARRANTY, NEGLIGENCE, STRICT LIABILITY, MISREPRESENTATIONS AND ANY AND ALL OTHER TORTS. YOU HEREBY RELEASE Beast Franchise™ FROM ANY AND ALL OBLIGATIONS, LIABILITIES AND CLAIMS IN EXCESS OF THE LIMITATIONS STATED HEREIN. IF APPLICABLE LAW DOES NOT PERMIT SUCH LIMITATION, THE MAXIMUM LIABILITY OF Beast Franchise™ TO YOU UNDER ANY AND ALL CIRCUMSTANCES WILL BE FIVE HUNDRED DOLLARS ($500.00). YOU HEREBY RELEASE Beast Franchise™ FROM ANY AND ALL OBLIGATIONS, LIABILITIES AND CLAIMS IN EXCESS OF THE LIMITATIONS SET FORTH IN THIS SECTION 18. NO ACTION, REGARDLESS OF FORM, ARISING OUT OF YOUR USE OF THE SITE, Beast Franchise™ SERVICES, Beast Franchise™ CONTESTS AND/OR Beast Franchise™ SHOP, ANY CONTENT, FEEDBACK, NEWS FEEDS, Beast Franchise™ SHOP PRODUCTS OR ANY OTHER PRODUCTS AND/OR SERVICES OFFERED THEREIN MAY BE BROUGHT BY YOU OR Beast Franchise™ MORE THAN ONE (1) YEAR FOLLOWING THE EVENT WHICH GAVE RISE TO THE CAUSE OF ACTION. THE NEGATION OF DAMAGES SET FORTH ABOVE IS A FUNDAMENTAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN YOU AND Beast Franchise™. ACCESS TO THE SITE, Beast Franchise™ SERVICES, Beast Franchise™ CONTESTS AND/OR Beast Franchise™ SHOP, ANY CONTENT, FEEDBACK, NEWS FEEDS, Beast Franchise™ SHOP PRODUCTS OR ANY OTHER PRODUCTS AND/OR SERVICES OFFERED THEREIN WOULD NOT BE PROVIDED TO YOU WITHOUT SUCH LIMITATIONS. Some jurisdictions do not allow certain limitations on liability and, in such jurisdictions, Beast Franchise’s™ liability shall be limited to the maximum extent permitted by law.



Contacting Us about Privacy Questions or Concerns
If you have any questions about this Privacy Policy, the practices of the Site, BEASTfranchise Shop, please e-mail us at BEAST@BEASTDOME.com or send a letter to.